s = "Tops Technologies"
print (s)

print(s.capitalize())
print(s.casefold())
print(s.center(50,"*"))
print(s.startswith("t"))
print(s.endswith("es"))
print(s.find("log"))
print("tops123".isalpha())
print("tops".isalpha())
print("tops123".isalnum())
print("123".isnumeric())
print("tops".islower())
print("tops".isupper())
print("Tops Techno".istitle())
print("hello".replace("l","w"))
